language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - 1.38.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  global:
    - RUSTFLAGS='-D warnings'
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi
before_script: |
  ([ "$TRAVIS_RUST_VERSION" == nightly ] || rustup component add rustfmt) &&
  ([ "$TRAVIS_RUST_VERSION" == nightly ] || rustup component add clippy)
# As a result of https://github.com/travis-ci/travis-ci/issues/1066, we run
# everything in one large command instead of multiple commands.
# In this way, the build stops immediately if one of the commands fails.
script: |
  cargo clean &&
  ([ "$TRAVIS_RUST_VERSION" == nightly ] || cargo fmt --all -- --check) &&
  ([ "$TRAVIS_RUST_VERSION" == nightly ] || cargo clippy) &&
  cargo build &&
  cargo test
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
